apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job-1
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: alpine
              imagePullPolicy: IfNotPresent
              name: alpine-sleep
              command: [ "/bin/sh" ]
              args: [ "-c", "sleep 180" ]
              resources:
                requests:
                  cpu: "0.3"
          restartPolicy: OnFailure
